server:
  port: 7082
  servlet:
    context-path: /bancoDataRest1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: bancoDataRest.log

spring:
  application:
    name: banco-data-rest1
  datasource:
    hikari:
      maximum-pool-size: 25
    url: jdbc:h2:file:./bancodatarest-app1;DB_CLOSE_ON_EXIT=TRUE
    platform: h2
    username: bancodatarest1
    password: bancodatarest1
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        jdbc:
          time_zone: UTC-3
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
info:
  app:
    name: project.name@
    description: project.description@
    version: project.version@
    encoding: project.build.sourceEncoding@
    java:
      version: "1.8"